services:
    php:
        image: ghcr.io/sylius/sylius-php:8.3-alpine
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        image: postgres:16
        environment:
            POSTGRES_DB: sylius
            POSTGRES_USER: sylius
            POSTGRES_PASSWORD: sylius
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U sylius -d sylius" ]
            interval: 5s
            timeout: 5s
            retries: 10
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
    nginx:
        image: ghcr.io/sylius/sylius-nginx:latest
    mailhog:
        # do not use in production!
        image: mailhog/mailhog:latest
